#!/usr/bin/env bash

# check for bucket name

if [ -z "$1" ]; then    
    echo "there needs to be bucket name"
    exit 1
fi 

if [ -z "$2" ]; then
    echo "there needs to be file name"
    exit 1
fi

BUCKET_NAME=$1
FILENAME=$2
OBJECT_KEY=$(basename "$FILENAME")

aws s3api delete-object \
--bucket $BUCKET_NAME \
--key $OBJECT_KEY

